services:
  configuration:
    container_name: configuration 
    build: ./configuration
    ports:
      - 8000:8000
    command: sleep infinity
    # command: sh -c "poetry install --no-root && poetry run fastapi run app/main.py"
    working_dir: /workspace/configuration/
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached

  configuration_db:
    image: mongo:8.0
    restart: always
    expose:
      - '27017'
    env_file:
      - ./configuration_db/.env
  
  configuration_db_control:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./configuration_db/.env

  llm_proxy:
    container_name: llm_proxy 
    build: ./llm_proxy
    expose:
      - "8000"
    # command: sleep infinity for debugging
    command: sh -c "poetry install --no-root && poetry run fastapi run app/main.py"
    working_dir: /workspace/llm_proxy/
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached

  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    restart: unless-stopped
    image: ollama/ollama:0.5.7
    expose:
      - "11434"  # Expose Ollama on the default port 
    post_start:
      - command: ollama pull deepseek-r1:1.5b
        user: root

volumes:
  ollama: {}
