services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    restart: unless-stopped
    image: ollama/ollama:0.5.7
    ports:
      - "11434:11434"  # Expose Ollama on the default port 
    post_start:
      - command: ollama pull deepseek-r1:1.5b
        user: root

volumes:
  ollama: {}
